// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/zenitu-designs/Cosmico.tsx": () => import("../components/mockups/zenitu-designs/Cosmico.tsx"),
  "./components/mockups/zenitu-designs/GalaxiaNeon.tsx": () => import("../components/mockups/zenitu-designs/GalaxiaNeon.tsx"),
  "./components/mockups/zenitu-designs/TropicalDourado.tsx": () => import("../components/mockups/zenitu-designs/TropicalDourado.tsx")
};
